version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing Packages...
      - npm install
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - config/*
    - models/*
    - migrations/*
    - node_modules/**/*
    - package.json
    - package-lock.json
    - server.js
